ALTER TABLE tasks ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES stakeholders(id) ON DELETE SET NULL;
ALTER TABLE actions ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES stakeholders(id) ON DELETE SET NULL;
ALTER TABLE risks ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES stakeholders(id) ON DELETE SET NULL;
ALTER TABLE milestones ADD COLUMN IF NOT EXISTS owner_id INTEGER REFERENCES stakeholders(id) ON DELETE SET NULL;
